name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy para AWS Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Instalar Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Compilar código Go
        run: |
          GOOS=linux GOARCH=amd64 go build -o main main.go
          zip function.zip main

      - name: Fazer deploy da função Lambda
        run: |
          aws lambda update-function-code \
            --function-name lambda-gh-action \
            --zip-file fileb://function.zip
